// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tms.Data.Context;

namespace Tms.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210816183802_SeedDemo")]
    partial class SeedDemo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Tms.Data.Domain.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedOnUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("FinishDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("TaskItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test task has Id = 001",
                            FinishDateUtc = new DateTime(2021, 9, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 001",
                            StartDateUtc = new DateTime(2021, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test task has Id = 002",
                            FinishDateUtc = new DateTime(2021, 9, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 002",
                            StartDateUtc = new DateTime(2021, 9, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Test task has Id = 003",
                            FinishDateUtc = new DateTime(2021, 9, 4, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 003",
                            StartDateUtc = new DateTime(2021, 9, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Test task has Id = 004",
                            FinishDateUtc = new DateTime(2021, 9, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 004",
                            StartDateUtc = new DateTime(2021, 9, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Test task has Id = 005",
                            FinishDateUtc = new DateTime(2021, 9, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 005",
                            StartDateUtc = new DateTime(2021, 9, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Test task has Id = 006",
                            FinishDateUtc = new DateTime(2021, 9, 7, 22, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 006 (parent)",
                            StartDateUtc = new DateTime(2021, 9, 7, 21, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Test subtask has Id = 007, parent Id = 007",
                            FinishDateUtc = new DateTime(2021, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Subtask 007",
                            ParentId = 6,
                            StartDateUtc = new DateTime(2021, 9, 2, 23, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Test subtask has Id = 008, parent Id = 008",
                            FinishDateUtc = new DateTime(2021, 9, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Subtask 008",
                            ParentId = 6,
                            StartDateUtc = new DateTime(2021, 9, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Test subtask has Id = 009, parent Id = 009",
                            FinishDateUtc = new DateTime(2021, 9, 5, 2, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Subtask 009",
                            ParentId = 6,
                            StartDateUtc = new DateTime(2021, 9, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Test subtask has Id = 010, parent Id = 010",
                            FinishDateUtc = new DateTime(2021, 9, 6, 3, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Subtask 010",
                            ParentId = 6,
                            StartDateUtc = new DateTime(2021, 9, 6, 2, 0, 0, 0, DateTimeKind.Utc),
                            State = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Test task has Id = 011",
                            FinishDateUtc = new DateTime(2021, 9, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 011 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Test task has Id = 012",
                            FinishDateUtc = new DateTime(2021, 9, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 012 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Test task has Id = 013",
                            FinishDateUtc = new DateTime(2021, 9, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 013 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Test task has Id = 014",
                            FinishDateUtc = new DateTime(2021, 9, 4, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 014 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Test task has Id = 015",
                            FinishDateUtc = new DateTime(2021, 9, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 015 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "Test task has Id = 016",
                            FinishDateUtc = new DateTime(2021, 9, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 016 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 17,
                            Description = "Test task has Id = 017",
                            FinishDateUtc = new DateTime(2021, 9, 7, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 017 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "Test task has Id = 018",
                            FinishDateUtc = new DateTime(2021, 9, 8, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 018 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 19,
                            Description = "Test task has Id = 019",
                            FinishDateUtc = new DateTime(2021, 9, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 019 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Test task has Id = 020",
                            FinishDateUtc = new DateTime(2021, 9, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Task 020 (InProgress)",
                            StartDateUtc = new DateTime(2021, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            State = 1
                        });
                });

            modelBuilder.Entity("Tms.Data.Domain.TaskItem", b =>
                {
                    b.HasOne("Tms.Data.Domain.TaskItem", "Parent")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Tms.Data.Domain.TaskItem", b =>
                {
                    b.Navigation("Subtasks");
                });
#pragma warning restore 612, 618
        }
    }
}
